name: Laravel CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate an application key
        run: php artisan key:generate

      - name: Run tests with PHPUnit
        run: vendor/bin/phpunit

      - name: Check coding standards with PHP CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 app

      - name: Check code quality with PHPStan
        run: vendor/bin/phpstan analyze
